### ISSUE TITLE
How to manage API key ?

### ISSUE THREAD

**Issue by nprime496** [quamernasim/Role-Based-Access-Control-of-Qdrant-Vector-Database#1]
Hi, thank you for your repo, quite straightforward, it is surprising that they do not provide such clear commands themselves.

However, I wonder how we should obtain the API key and how to store it ?
Will every user for a role have the same key ?

**Comment by quamernasim** [comment]
Hi, apologies for late response. I have provided a function that creates the JWT tokens which can be passed in the API key argument. See the below example

```
import jwt
def generate_jwt(api, payload):
   '''
   This function generates a JWT token using the payload and the API key

   Args:
   api: API key
   payload: Payload to be encoded in the JWT token. It contains the access rights

   Returns:
   encoded_jwt: JWT token
   '''
   encoded_jwt = jwt.encode(payload, api, algorithm='HS256')
   return encoded_jwt
   
   
import time
from utils import generate_jwt

current_time = int(time.time())

# This payload along with the API is used to generate the JWT token.
# This token tells that the user has global read only access to all the collections.
# It also specifies that this token will expire in 1 hour.
payload = {
 "access": "r",
 "exp": current_time + 3600, # 1 hour
}

# Generate the JWT token
# This token will be used to authenticate the user.
jwt = generate_jwt(api, payload)
```

using the above function you can create the API key for users. All users will have their own key, it's same as how ssh-key is provided for every user. You create the key based on their access level, share it with them, and they can have it in env variable or in config.yaml itself as shown in the repo

**Comment by quamernasim** [comment]
this si not addressed
